### ISSUE TITLE
isExact and union types

### ISSUE THREAD

**Issue by johan13** [ts-essentials/ts-essentials#342]
When I try to compile this snipped with Typescript 4.9.4:
```ts
import { isExact } from "ts-essentials";

declare const value1: number;
declare const value2: number | undefined;
isExact<number>()(value1);             // Works
isExact<number | undefined>()(value2); // Doesn't work
```

I get the error:
```
test.ts:6:31 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'undefined'.
  Type 'number' is not assignable to type 'undefined'.

6 isExact<number | undefined>()(value2); // Doesn't work
                                ~~~~~~
```

Is this a bug? Or is `isExact` only expected to work with object types?

**Comment by johan13** [comment]
I have been using [ts-expect](https://github.com/TypeStrong/ts-expect) previously. ts-expect handles this case correctly, but it doesn't handle enums well. ts-essentials isExact works with enums but doesn't seem to handle `| undefined` the way I expected. :confused:

**Comment by Beraliv** [comment]
Hey @johan13!

Thank you for the reported issue!

We didn't add covering types (tests) for last 2 versions (4.8 and 4.9), let me do it just in case it's something from the new TypeScript version

Otherwise, I got your examples in Playground – https://tsplay.dev/N72qrw, I will add these tests in the repo and let me take some time to investigate it further

I will let you know this week

**Comment by Beraliv** [comment]
Apologies for the late response, I'm going to revisit this later today

**Comment by Beraliv** [comment]
I've checked it https://github.com/ts-essentials/ts-essentials/pull/344, types work the same for TypeScript 4.8 & 4.9

**Comment by Beraliv** [comment]
I've checked that we only tested `isExact` with object types

Currently I see `Exact<number | undefined, number | undefined>` returns `undefined` instead of `never`, that's why you get TS error

I fixed it in https://github.com/ts-essentials/ts-essentials/pull/345

Could you please validate that new implementation works as expected for you? I've added same tests so it should be identical, but maybe you have other examples to test

**Comment by johan13** [comment]
Thank you!

I have verified that the PR fixes the code I had problems with originally, but you are right - it doesn't fix this case from my comment above:
```ts
isExact<{ xyz: number | undefined }>()(obj1); // OK - but shouldn't match!
```

**Comment by Beraliv** [comment]
I've updated the implementation in the PR, let me know if that's exactly what you need (it looks complicated though)

**Comment by johan13** [comment]
`| undefined` work fine now. But it looks like arrays are broken instead.

This code works fine in `master` but fails in `fix/isExact-and-union-types`:

```ts
declare const foo: number[];
isExact<number[]>()(foo);
```

**Comment by johan13** [comment]
By the way, I was playing around with `isExact` and the `readonly` keyword and found another unexpected behavior. This is in master and perhaps unrelated to this bug, but I thought I'd mention in connection to this anyway.

```ts
// Readonly arrays work fine:
declare const rwArray: number[];
declare const roArray: readonly number[];
isExact<number[]>()(rwArray);
isExact<readonly number[]>()(roArray);
// @ts-expect-error
isExact<number[]>()(roArray);
// @ts-expect-error
isExact<readonly number[]>()(rwArray);

// But readonly is ignored for object properties:
declare const rwObj: { foo: number };
declare const roObj: { readonly foo: number };
isExact<{ foo: number }>()(rwObj);
isExact<{ readonly foo: number }>()(roObj);
// @ts-expect-error
isExact<{ readonly foo: number }>()(rwObj);
// @ts-expect-error
isExact<{ foo: number }>()(roObj);
```
I would expect the last to `isExact` to fail - but they don't. (I get two `Unused '@ts-expect-error' directive` errors.)

**Comment by Beraliv** [comment]
@johan13 thank you for checking so many edge cases, I'm on it, let me come back to you with the solution!

**Comment by Beraliv** [comment]
> By the way, I was playing around with `isExact` and the `readonly` keyword and found another unexpected behavior. This is in master and perhaps unrelated to this bug, but I thought I'd mention in connection to this anyway.
> 
> ```ts
> // Readonly arrays work fine:
> declare const rwArray: number[];
> declare const roArray: readonly number[];
> isExact<number[]>()(rwArray);
> isExact<readonly number[]>()(roArray);
> // @ts-expect-error
> isExact<number[]>()(roArray);
> // @ts-expect-error
> isExact<readonly number[]>()(rwArray);
> 
> // But readonly is ignored for object properties:
> declare const rwObj: { foo: number };
> declare const roObj: { readonly foo: number };
> isExact<{ foo: number }>()(rwObj);
> isExact<{ readonly foo: number }>()(roObj);
> // @ts-expect-error
> isExact<{ readonly foo: number }>()(rwObj);
> // @ts-expect-error
> isExact<{ foo: number }>()(roObj);
> ```
> 
> I would expect the last two `isExact` to fail - but they don't. (I get two `Unused '@ts-expect-error' directive` errors.)

Thank you for your examples, I've added more tests cases in this commit – https://github.com/ts-essentials/ts-essentials/pull/345/commits/bd21f5343c8419688485b44e32e91a65e329c9fd, will try to fix them this week

I will keep you updated

**Comment by Beraliv** [comment]
@johan13 I think I fixed readonly/writable arrays in https://github.com/ts-essentials/ts-essentials/pull/345/commits/edc9221f6cfc9be3443c7f74eab2738785b050c5

Can you please review it again? CI checks are green now

**Comment by johan13** [comment]
Thanks @Beraliv.

Now both `| undefined` and arrays work. But enums appear to be broken instead. At least string enums with more than one value:

```ts
enum SingleEnum { Foo = "foo" }
enum MultipleEnum { Foo = "foo", Bar = "bar", Baz = "baz" }

const e1 = SingleEnum.Foo;
const e2 = MultipleEnum.Foo;

isExact<SingleEnum>()(e1);   // This still works.
isExact<MultipleEnum>()(e2); // This used to work, but fails now.
```

I get `TS2345: Argument of type 'MultipleEnum' is not assignable to parameter of type 'never'.` on the second `isExact`.

**Comment by Beraliv** [comment]
> Thanks @Beraliv.
> 
> But enums appear to be broken instead. At least string enums with more than one value:
> 
> ```ts
> enum SingleEnum { Foo = "foo" }
> enum MultipleEnum { Foo = "foo", Bar = "bar", Baz = "baz" }
> 
> const e1 = SingleEnum.Foo;
> const e2 = MultipleEnum.Foo;
> 
> isExact<SingleEnum>()(e1);   // This still works.
> isExact<MultipleEnum>()(e2); // This used to work, but fails now.
> ```
> 
> I get `TS2345: Argument of type 'MultipleEnum' is not assignable to parameter of type 'never'.` on the second `isExact`.

I will check them next! Thanks for the test cases again!

**Comment by Beraliv** [comment]
Technically `isExact<SingleEnum>()(e1);` and `isExact<MultipleEnum>()(e2);` should NOT be both working as `SingleEnum` isn't the same as `SingleEnum.One`, same for `MultipleEnum`

But I can accept that it's convenient to use `SingleEnum` and `MultipleEnum` instead of `SingleEnum.One` and `MultipleEnum.One`

Even though I will change it to this, it won'y work so it requires a fix:

```ts
const e1: SingleEnum = SingleEnum.Foo;
const e2: MultipleEnum = MultipleEnum.Foo;
```

**Comment by johan13** [comment]
Yes, you are right. I should have specified the enum type to avoid getting a too narrow type there.

**Comment by johan13** [comment]
@Beraliv, did you ever find a solution to this?

**Comment by Beraliv** [comment]
Hey @johan13!

Apologies for the late response

It's still on my list but I didn't have a chance to finish it

**Comment by Beraliv** [comment]
@johan13 I will have a look at issue again and will come back to you when I have a fix

**Comment by Beraliv** [comment]
Hey @johan13 I'd like to keep it imcremental and merge as much as possible before reiterating. Don't you mind creating a separate bug for enums? Is there any other test cases that are broken for you apart from enums?

**Comment by Beraliv** [comment]
This change has been merged and added to the next major release - https://github.com/ts-essentials/ts-essentials/pull/386, it will be deployed by the end of April

**Comment by Beraliv** [comment]
It's released just now as a part of [v10.0.0](https://github.com/ts-essentials/ts-essentials/releases/tag/v10.0.0)
